<?php

/**
 * @file
 * Contains toolbar_tasks.module.
 */
use Drupal\Core\Url;

/**
 * Implements hook_toolbar().
 */
function toolbar_tasks_toolbar() {

  // Do not show tabs when on the admin theme.
  $admin_context = \Drupal::service('router.admin_context');
  if ($admin_context->isAdminRoute()) {
    return;
  }

  $manager = \Drupal::service('plugin.manager.menu.local_task');
  $tasks = $manager->getLocalTasks(\Drupal::routeMatch()->getRouteName());
  $subtree_tasks = array();
  foreach ($tasks['tabs'] as $key => $tab) {
    $subtree_tasks[$key] = array(
      'title' => $tab['#link']['title'],
      'url' => $tab['#link']['url'],
      'weight' => $tab['#weight'],
    );
  }

  $items['primary_tasks'] = array(
    '#type' => 'toolbar_item',
    'tab' => array(
      '#type' => 'link',
      '#title' => t('Page Actions'),
      '#url' => Url::fromRoute('<front>'),
      '#attributes' => array(
        'title' => t('Home page'),
        'class' => array('toolbar-icon', 'toolbar-icon-edit'),
      ),
    ),
    'tray' => array(
      '#heading' => t('Page actions'),
      'toolbar_actions' => array(
        '#type' => 'container',
        '#attributes' => array(
          'class' => array('toolbar-menu-administration'),
        ),
        '#theme' => 'menu_local_tasks',
        '#primary' => $tasks['tabs'],
      ),
    ),
    '#cache' => array(
      'contexts' => array('user.permissions', 'url.path'),
    ),
  );

  return $items;
}

 /**
 * Implements hook_page_attachments().
 */
function toolbar_tasks_page_attachments(array &$attachments) {
  $admin_context = \Drupal::service('router.admin_context');
  if (!$admin_context->isAdminRoute()) {
    $attachments['#attached']['library'][] = 'toolbar_tasks/toolbar';
  }
}